### ISSUE TITLE
just to let u know

### ISSUE THREAD

**Issue by rishabharidas** [Aakarsh-B/Aakarsh-B#1]
![image](https://user-images.githubusercontent.com/22971553/108831881-bee1c500-75f0-11eb-866d-e33dcfb0bbde.png)
why is this like this?

**Comment by Aakarsh-B** [comment]
The repo I had my images in was private. I could see the images, others couldn't. 
I didn't know this.
I think this would fix the issue.
Do lemme know

**Comment by rishabharidas** [comment]
some are... bro


![image](https://user-images.githubusercontent.com/22971553/109002165-da6dce00-76cb-11eb-9ebe-1926670adb30.png)

**Comment by Aakarsh-B** [comment]
is it alright now?
